### ISSUE TITLE
Feature Request: Add disabledAfterToday prop

### ISSUE THREAD

**Issue by KPS250** [huurray/react-native-calendar-range-picker#13]
It would be really great if you can add this prop so as to avoid future date range selection in required scenarios where we need to select today & past date.

OR 

Is there any way to exclude future months ?

**Comment by official-ravi** [comment]
@KPS250 are you able to figure out something to get future dates disabled?

**Comment by PrathapKaraka** [comment]
I need the same now. anyone figuredout?

**Comment by huurray** [comment]
added disabledAfterToday prop. sorry for late.
