### ISSUE TITLE
react native fullScreen notification incoming call

### ISSUE THREAD

**Issue by chganesh** [huurray/react-native-calendar-range-picker#39]
![download-_1_](https://user-images.githubusercontent.com/14010143/206196385-d4bdbc1a-74b0-4805-85d2-ddd1e72e7824.jpeg)
 Any suggestion for Incoming call notification full screen while lock screen state and notification popup awake the device. please help on this need to work both platforms.  
![download](https://user-images.githubusercontent.com/14010143/206195597-99506f09-faec-4fc1-8adf-b0463f3d3845.png)

**Comment by chganesh** [comment]
while getting Firebase push notification that time need display this kind of notification popup and full screen while lock screen.

**Comment by huurray** [comment]
@chganesh I think you posted an issue with another library here. This library provides a calendar.
