### ISSUE TITLE
Invariant Violation - Invalid Hook Call

### ISSUE THREAD

**Issue by nabilnalakath** [huurray/react-native-calendar-range-picker#4]
I am getting the following error when I try to include the calendar in my project. I am displaying the calendar view dynamically on a button click. The page loads fine initially, but as soon as I click on the button to show the calendar view I am getting the following error.

![image](https://user-images.githubusercontent.com/32065631/93952626-efce7d00-fd66-11ea-8332-0b993ae99a76.png)

**Comment by huurray** [comment]
can i see your code you add calendar picker?

**Comment by shaikhaffan** [comment]
@huurray I am also facing similar issue

example:
import Calendar from "react-native-calendar-range-picker";

const StayBookingCalenderComponent = (props) => {

    return (
        <View style={{flex:1}}>
        <Calendar
        startDate="2020-05-05"
        endDate="2020-05-12"
        onChange={({ startDate, endDate }) => console.log({ startDate, endDate })}
        />
</View>
       
    )
        
}

export default StayBookingCalenderComponent

**Comment by nabilnalakath** [comment]
@huurray I think it may be due to different react versions used within the package.json. I am using react 16.13.1, and I see that in your package.json you have fixed it to react 16.8.6. Could you please update your version or make it compatible with the auto-update of dependencies.  I found that this may be the cause of the error here - [Invalid Hook Call Warning](https://reactjs.org/warnings/invalid-hook-call-warning.html). Also attaching a screenshot of my **npm ls react** result.

<img width="435" alt="Screenshot 2020-09-25 at 4 45 30 PM" src="https://user-images.githubusercontent.com/32065631/94260874-8c06a880-ff4e-11ea-9b7c-8ca4f7e02040.png">

**Comment by minuitagency** [comment]
same issue here

**Comment by huurray** [comment]
I released 1.5.0 version to fix this issue. I'm so sorry to be late!
