### ISSUE TITLE
backgroundColor issue

### ISSUE THREAD

**Issue by giannismanie** [huurray/react-native-calendar-range-picker#45]
When we set the background color using 'monthContainer: { backgroundColor: colors.primary }', there are instances where the month container appears with a white color, as depicted in the following screenshot.
Tried also to use on 'container' the backgroundColor but did not work at all.

![Screenshot](https://github.com/huurray/react-native-calendar-range-picker/assets/43655664/d7127641-681b-464a-9745-bcc30ce0fbe0)

**Comment by huurray** [comment]
@giannismanie I got some wrong code. i fixed it v1.5.8. please update the version and in that case, use 'container' style with the backgroundColor.
