### ISSUE TITLE
How to change year - month to month - year?

### ISSUE THREAD

**Issue by schnetzlerjoe** [huurray/react-native-calendar-range-picker#6]
Hello! How would one change year - month to month-year? Is that a possible change? Would be very useful!

**Comment by huurray** [comment]
Hello! i update the package to v1.5.2 and add "isMonthFirst" prop.
this can help you to switch year and month order. check README.md!!
thanks!

**Comment by schnetzlerjoe** [comment]
Great! Amazing package. Thank you.
